apiVersion: v1
kind: ConfigMap
metadata:
  name: quay-provisioner-pipelines
data:
  inputs.yaml: |
    organizations:
      - name: test
        visibility: private
        email: test@test.ch
        owner: test

    robot_accounts:
      - organization: test
        robot_shortname: ci-bot
        description: CI automation bot

  pipeline.yaml: |
    pipeline:
      - name: create-organizations
        job: create_organization
        enabled: true
        params_list: "{{ inputs.organizations }}"
      - name: create-robot-accounts
        job: create_robot_account
        enabled: true
        params_list: "{{ inputs.robot_accounts }}"