{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
  QUAY_API_BASE_URL: "{{ .Values.secrets.apiBaseUrl }}"
  QUAY_API_TOKEN: "{{ .Values.secrets.apiToken }}"
{{- end }}